config.h: Include stddef.h for size_t
Address the following clang-tidy issue:

```
Error while processing .../obmc-console/config.h.
.../obmc-console/config.h:36:49: error: unknown type name 'size_t' [clang-diagnostic-error]
   36 | int config_parse_bytesize(const char *size_str, size_t *size);
      |                                                 ^
```

Fixes: 1e04f449b7f0 ("use iniparser dependency for config file parsing")
Change-Id: I22adfc548d1f8837fda8920267a16e93c17c8475
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>