obmc-console: Fix readability-inconsistent-declaration-parameter-name
```
/usr/bin/clang-tidy -checks=-*, readability-inconsistent-declaration-parameter-name -export-fixes /tmp/tmppaj3mheq/tmphdn64rrm.yaml -p=build /mnt/host/andrew/home/andrew/src/openbmc/obmc-console/console-server.c
../console-server.h:82:16: error: function 'console_poller_register' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
struct poller *console_poller_register(struct console *console,
               ^
../console-server.c:538:16: note: the definition seen here
struct poller *console_poller_register(struct console *console,
               ^
/mnt/host/andrew/home/andrew/src/openbmc/obmc-console/build/../console-server.h:82:16: note: differing parameters are named here: ('event_fn'), in definition: ('poller_fn')
struct poller *console_poller_register(struct console *console,
               ^
/mnt/host/andrew/home/andrew/src/openbmc/obmc-console/build/../console-server.h:93:6: error: function 'console_poller_set_timeout' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
void console_poller_set_timeout(struct console *console, struct poller *poller,
     ^
../console-server.c:644:6: note: the definition seen here
void console_poller_set_timeout(struct console *console __attribute__((unused)),
     ^
/mnt/host/andrew/home/andrew/src/openbmc/obmc-console/build/../console-server.h:93:6: note: differing parameters are named here: ('interval'), in definition: ('tv')
void console_poller_set_timeout(struct console *console, struct poller *poller,
     ^
5 warnings generated.
```

Signed-off-by: Andrew Jeffery <andrew@aj.id.au>
Change-Id: Ic9910bc7e716477b8e0eb0e40f32567972cc4529